### PR TITLE
Use a single name when loading from store

### LINKED ISSUE #203: Assertion in OpenSSL when loading a key from the provider
**Describe the bug**
OpenSSL (debug version) asserts and terminates when loading a key from the provider.

This is the backtrace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at ./nptl/pthread_kill.c:44
#1  0x00007ffff7914d2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff78c5ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff78b0472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7c79d62 in OPENSSL_die (
    message=0x7ffff7de6f98 "Assertion failed: name_id > 0 && name_id <= METHOD_ID_NAME_MAX",
    file=0x7ffff7de6f80 "crypto/evp/evp_fetch.c", line=132) at crypto/cryptlib.c:260
#5  0x00007ffff7c48c09 in ossl_assert_int (expr=0,
    exprstr=0x7ffff7de6f98 "Assertion failed: name_id > 0 && name_id <= METHOD_ID_NAME_MAX",
    file=0x7ffff7de6f80 "crypto/evp/evp_fetch.c", line=132) at include/internal/cryptlib.h:38
#6  0x00007ffff7c48db4 in evp_method_id (name_id=0, operation_id=10) at crypto/evp/evp_fetch.c:132
#7  0x00007ffff7c49577 in inner_evp_generic_fetch (methdata=0x7fffffffdb40, prov=0x55555567cd80, operation_id=10,
    name_id=0, name=0x7ffff7872aa0 "RSA:rsaEncryption:1.2.840.113549.1.1.1", properties=0x0,
    new_method=0x7ffff7c55028 <keymgmt_from_algorithm>, up_ref_method=0x7ffff7c55781 <EVP_KEYMGMT_up_ref>,
    free_method=0x7ffff7c557ba <EVP_KEYMGMT_free>) at crypto/evp/evp_fetch.c:355
#8  0x00007ffff7c49741 in evp_generic_fetch (libctx=0x0, operation_id=10,
    name=0x7ffff7872aa0 "RSA:rsaEncryption:1.2.840.113549.1.1.1", properties=0x0,
    new_method=0x7ffff7c55028 <keymgmt_from_algorithm>, up_ref_method=0x7ffff7c55781 <EVP_KEYMGMT_up_ref>,
    free_method=0x7ffff7c557ba <EVP_KEYMGMT_free>) at crypto/evp/evp_fetch.c:396
#9  0x00007ffff7c5577b in EVP_KEYMGMT_fetch (ctx=0x0,
    algorithm=0x7ffff7872aa0 "RSA:rsaEncryption:1.2.840.113549.1.1.1", properties=0x0) at crypto/evp/keymgmt_meth.c:230
#10 0x00007ffff7cfcc46 in try_key_ref (data=0x7fffffffdcd0, ctx=0x5555556d2540, provider=0x55555567e0a0, libctx=0x0,
    propq=0x0) at crypto/store/store_result.c:200
#11 0x00007ffff7cfd1fa in try_key (data=0x7fffffffdcd0, v=0x7fffffffded0, ctx=0x5555556d2540, provider=0x55555567e0a0,
    libctx=0x0, propq=0x0) at crypto/store/store_result.c:398
#12 0x00007ffff7cfc994 in ossl_store_handle_load_result (params=0x7fffffffdde0, arg=0x7fffffffded0)
    at crypto/store/store_result.c:134
#13 0x00007ffff786c7f4 in p11prov_store_load (pctx=0x55555566fa60, object_cb=<optimized out>,
    object_cbarg=0x7fffffffded0, pw_cb=0x7ffff7c871e6 <ossl_pw_passphrase_callback_dec>, pw_cbarg=<optimized out>)
    at store.c:360
#14 0x00007ffff7cf9492 in OSSL_STORE_load (ctx=0x5555556d2540) at crypto/store/store_lib.c:428
#15 0x000055555560212d in load_key_certs_crls_suppress (
    uri=0x7fffffffe9a6 "pkcs11:type=private;object=TESTRSA?pin-value=1111", format=0, maybe_stdin=0, pass=0x0,
    desc=0x55555561b648 "signing key", ppkey=0x7fffffffe120, ppubkey=0x0, pparams=0x0, pcert=0x0, pcerts=0x0,
    pcrl=0x0, pcrls=0x0, suppress_decode_errors=0) at apps/lib/apps.c:972
#16 0x00005555556026f9 in load_key_certs_crls (uri=0x7fffffffe9a6 "pkcs11:type=private;object=TESTRSA?pin-value=1111",
    format=0, maybe_stdin=0, pass=0x0, desc=0x55555561b648 "signing key", ppkey=0x7fffffffe120, ppubkey=0x0,
    pparams=0x0, pcert=0x0, pcerts=0x0, pcrl=0x0, pcrls=0x0) at apps/lib/apps.c:1099
#17 0x0000555555600f7d in load_key (uri=0x7fffffffe9a6 "pkcs11:type=private;object=TESTRSA?pin-value=1111", format=0,
    may_stdin=0, pass=0x0, e=0x0, desc=0x55555561b648 "signing key") at apps/lib/apps.c:560
#18 0x00005555555abafe in cms_main (argc=0, argv=0x7fffffffe6b0) at apps/cms.c:1078
#19 0x00005555555c3347 in do_cmd (prog=0x55555567dee0, argc=10, argv=0x7fffffffe660) at apps/openssl.c:418
#20 0x00005555555c2f10 in main (argc=10, argv=0x7fffffffe660) at apps/openssl.c:298
```

**To Reproduce**
Use any test that loads a key and run it with debug version of OpenSSL (e.g. _tsession_ test is good enough).

**Expected behavior**
The assertion is not hit.

**Operating environment (please complete the following information):**
 - OS: Debian
 - Version: Testing

**Token and application used (please complete the following information):**
 - Device: SoftHSM2 2.6.1
 - PKCS11 Driver version: 2.6.1
 - Application: OpenSSL
 - Version: 3.0.8 (locally built debug version)

**Additional context**
I guess this is the consequence of passing _invalid_ `OSSL_OBJECT_PARAM_DATA_TYPE` back to the store object callback. Although I haven't found it documented anywhere I believe the data type string the provider is now using (e.g. `RSA:rsaEncryption:1.2.840.113549.1.1.1`) contains multiple aliases and that colon is the separator. Thus the provider should IMHO use a single identifier (e.g. `RSA`) as it can be seen in [fake_rsaprov.c](https://github.com/openssl/openssl/blob/cd870db16348d0d09cb05b7393cf9281509c7795/test/fake_rsaprov.c#L422-L423)

### PR DESCRIPTION
**Pull request by simo5**
Fixes #203

### CODE REVIEW

**Comment by simo5** [comment]
@manison can you check if this fixes the issue for you?

**Comment by manison** [comment]
This PR solves the loading part. Then when using the loaded key for signing I also had to change the operation names from plural to singular (`query_operation_name` methods in _keymgmt.c_).

**Comment by simo5** [comment]
@manison can you be more precise, what did you need to change exactly ?

Is this the reply from functions like p11prov_rsa_query_operation_name() ?
Sounds reasonable I guess...

**Comment by simo5** [comment]
Updated with single names everywhere I think it makes sense to.
Which is everywhere except OSSL_ALGORITHM structs...

**Comment by manison** [comment]
> Is this the reply from functions like p11prov_rsa_query_operation_name() ?

Exactly.

> Updated with single names everywhere I think it makes sense to.

Seems OK to me, will test.

**Comment by manison** [comment]
I ran tests against debug version of OpenSSL without this PR (failing) and with this PR applied and now all tests are passing. I consider #203 solved.

**Comment by simo5** [comment]
Thanks for testing!

**Pull request merged**
