### PR TITLE
tests: Use LeakSanitizer to catch future memory leaks

### PR DESCRIPTION
**Pull request by Jakuje**
#### Description

Follow-up to #471. The address sanitizer should catch memory leaks, but it needs the configuration, which was missing

https://clang.llvm.org/docs/LeakSanitizer.html

#### Reviewer's checklist:

- [x] Any issues marked for closing are addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- [ ] ~This feature/change has adequate documentation added~
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible commit messages
- [ ] ~Coverity Scan has run if needed (code PR) and no new defects were found~

### CODE REVIEW

**Review by neverpanic — APPROVED** [review]

**Comment by simo5** [comment]
@jakuje as you are fixing tests, would you mind adding --features standard to kryoptic builds to fix the kryoptic CI as well ?

**Comment by Jakuje** [comment]
> @Jakuje as you are fixing tests, would you mind adding --features standard to kryoptic builds to fix the kryoptic CI as well ?

I started in #473 simplifying the kryoptic build to use dynamic feature, but we need the standard too, which I forgot on first try. Changed now. But it still does not work. Trying now here only the `standard` feature.

**Comment by simo5** [comment]
@Jakuje .github/workflows/integration.yml needs the same treatment

**Comment by Jakuje** [comment]
> @Jakuje .github/workflows/integration.yml needs the same treatment

Added. Missed that one.

**Pull request merged**
