### PR TITLE
Extend the ttls test to be able to test different configurations

### PR DESCRIPTION
**Pull request by Jakuje**
#### Description

The TLS tests now tests just the default parameters with RSA key. This PR extends it to test also TLS 1.2, ECDSA keys and specific ciphersuites.

#### Checklist

- [X] Test suite updated with functionality tests

#### Reviewer's checklist:

- [ ] Any issues marked for closing are addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- [x] This feature/change has adequate documentation added
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible commit messages
- [ ] Coverity Scan has run if needed (code PR) and no new defects were found

### CODE REVIEW

**Comment by Jakuje** [comment]
Removed the commit that made it failing all over the place and keeping just the fixups that should make the CI pass (except for mac?) and that should be generally useful.

The commit making all of that failing is available in the wip branch https://github.com/Jakuje/pkcs11-provider/commits/ttls-test-wip/ and I believe they might be useful for reproducing further TLS issues.

**Comment by simo5** [comment]
Uhm in the second macos test faile di see that softhsm setup fails, but softokn and kryoptic setups succeed, yet *all* tests are skipped, would you happen to know why ?

**Comment by neverpanic** [comment]
@Jakuje Sorry for the delay on this – I checked out this branch, built it locally and ran the tests, and they all pass on my system. This either means that the issue isn't easily reproducible, or it only happens with components from Homebrew (I use MacPorts).

If you don't have any idea what's going on I can spend some more time to investigate and attempt to reproduce, but that will involve actually setting up a macOS VM, so unless we have no further avenues to follow up on, I'd like to avoid this.

**Comment by Jakuje** [comment]
Sounds like the issue was with the server that I did not kill it after each test. For some reason, it did not matter for linux, but did for macos. Now all looks green, except for the coverity, which I think is not relevant for this change.

**Comment by simo5** [comment]
The coverity scan is "failed" because it detected a code change after the covscan-ok label was set.

**Comment by simo5** [comment]
But there is no code change, so that's odd, I will have to recheck the logic in the CI automation, I will manually set the label after review

**Review by simo5 — APPROVED** [review]
LGTM

**Pull request merged**
