### PR TITLE
Fix ECDSA signatures and improve tests

### PR DESCRIPTION
**Pull request by fabled**
- Add test for ECDSA verify using openssl algorithm
- Add test for EC/SHA2 CSR
- Add verify for RSA CSR

### CODE REVIEW

**Comment by fabled** [comment]
@simo5 Any ideas why the softhsm tests fail now?

**Comment by fabled** [comment]
Fixed test to verify CSR instead. Turns out the ECDSA signature is likely wrong.

**Comment by fabled** [comment]
Ok, updated the earlier EC signing test to use also openssl software verify of the signature. This fails.

PKCS#11 ECDSA returns `2nLen` blob. OpenSSL wants DER encoded ECDSASignature. So the Sign/Verify needs to convert back and forth these formats for `CKM_ECDSA`.

**Comment by simo5** [comment]
To be honest I am surprised that we have to manually encode this.
I would assume the pkcs#11 tokens should do the encoding themselves, unless someone intentionally uses a raw signature mechanism and handrolls the rest.

**Comment by fabled** [comment]
> To be honest I am surprised that we have to manually encode this.
> I would assume the pkcs#11 tokens should do the encoding themselves, unless someone intentionally uses a raw signature mechanism and handrolls the rest.

The PKCS11 current mechanisms specifies that the signature is in raw format, see:
http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850447

**Review by simo5 — APPROVED** [review]
I see this is only format conversion in the end, pity that pkcs#11 does not do ASN.1, otoh it is also a good thing it doesn't.

LGTM.

**Pull request merged**
