### PR TITLE
Add demoCA tests to test certificate signing

### LINKED ISSUE #101: Add tests for openssl ca / openssl ocsp operations
Once we have a version of OpenSSL that includes https://github.com/openssl/openssl/pull/19648 or equivalent we should add tests that insure no regressions on CA cert manipulation.

Good examples are contained in issues #94 and #99

### PR DESCRIPTION
**Pull request by simo5**
Fixes #101

### CODE REVIEW

**Comment by simo5** [comment]
@beldmit would you be able to tell why this is failing in Debian?
The log spits all the right output, including saying the cert is good ... but then the openssl command exits with 127 ?

**Comment by simo5** [comment]
Output of the failing test on Debian:
```
Executing ./tdemoca

## Set up demoCA

## Generating CA cert if needed

## Generating a new CSR
..............+..+...+.......+.....+.+.....+.+...+...+.................+......+...............+....+............+.........+..+.......+.....+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+..+....+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...........+.+...............+..+...+...+.+...+.................+......+....+...+..+......+.......+......+.....+.......+..+.......+.....+................+..+...+.........+.............+......+..+....+.....+...+...+...+....+........+...+.+.....+...+......+.......+...+..+...+......+.+..+.............+..............+....+..............+...+....+......+..+.+......+........+...............+..........+..+...+......+.+...+...........+............+.......+..+....+.....+....+.....+...+.......+.....+......+......+..........+......+.....+..........+...+..+...+.........+.......+........+.+............+..+..........+...+........+......+.+..+...+...+.......+.....+...+............+..........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
....+.+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+......+......+......+.......+...+.................+.+.....+.+...........+....+.....+...+.......+......+...+.....+.........+...+...+......+....+.....+......+.+..+..........+.....+.......+........+.+......+......+...+.....+...................+...+..+.............+...+..+.............+......+.....+....+...............+..+...+..........+.....+.+.....+.+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----

## Signing the new certificate
Using configuration from /__w/pkcs11-provider/pkcs11-provider/tests/tmp.softokn/openssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'testing-csr-signing'
organizationName      :ASN.1 12:'PKCS11 Provider'
countryName           :PRINTABLE:'US'
Certificate is to be certified until Feb 20 23:16:44 2024 GMT (365 days)
801B5EA0667F0000:error:40800091:pkcs11:p11prov_GetOperationState:There is no active operation of appropriate type in the specified session:interface.gen.c:279:Error returned by C_GetOperationState

Write out database with 1 new entries
Data Base Updated

## Set up OCSP
Using configuration from /__w/pkcs11-provider/pkcs11-provider/tests/tmp.softokn/openssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'OCSP'
organizationName      :ASN.1 12:'PKCS11 Provider'
countryName           :PRINTABLE:'US'
Certificate is to be certified until Feb 20 23:16:45 2024 GMT (365 days)
801B3DB32D7F0000:error:40800091:pkcs11:p11prov_GetOperationState:There is no active operation of appropriate type in the specified session:interface.gen.c:279:Error returned by C_GetOperationState

Write out database with 1 new entries
Data Base Updated

## Run OCSP
ACCEPT 0.0.0.0:12345 PID=7983
ocsp: waiting for OCSP client connections...
ocsp: Received request, 1st line: POST / HTTP/1.0
OCSP Request Data:
    Version: 1 (0x0)
    Requestor List:
        Certificate ID:
          Hash Algorithm: sha1
          Issuer Name Hash: 810C6D581B88B8245F66B67E49B738D99BD5F7BB
          Issuer Key Hash: EC6A93F2479168957F9E94A3C633A0341E273171
          Serial Number: 01
    Request Extensions:
        OCSP Nonce: 
            0410F4E71463A3E6C1013B9CFCF0C8CEA11D
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = PKCS11 Provider, CN = OCSP
    Produced At: Feb 20 23:16:45 2023 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 810C6D581B88B8245F66B67E49B738D99BD5F7BB
      Issuer Key Hash: EC6A93F2479168957F9E94A3C633A0341E273171
      Serial Number: 01
    Cert Status: good
    This Update: Feb 20 23:16:45 2023 GMT

    Response Extensions:
        OCSP Nonce: 
            0410F4E71463A3E6C1013B9CFCF0C8CEA11D
    Signature Algorithm: sha1WithRSAEncryption
    Signature Value:
        31:2e:cb:48:d9:a5:e1:80:21:d0:d2:ad:65:e7:97:b9:46:69:
        f2:26:fa:a1:14:b6:49:89:aa:fa:45:97:f3:03:d5:8f:cc:c1:
        a5:83:5e:8f:f5:98:3c:1d:8b:2c:54:c6:cc:dc:26:52:35:fe:
        6e:40:25:ae:cd:33:15:3c:ac:ee:26:ff:43:7d:90:34:65:7a:
        d2:fd:04:c4:fe:d7:5b:7e:91:93:91:06:ac:51:1b:25:b0:e3:
        bf:cf:d1:db:01:5b:09:85:55:e0:97:60:5a:95:57:80:dd:0c:
        a1:f7:a8:1f:90:41:c0:30:b9:d4:b1:c5:ed:f9:11:1a:cd:d1:
        90:1a:83:ed:0b:cf:1e:24:05:77:c2:58:66:00:35:4c:c6:36:
        33:6b:e9:7c:97:04:9c:1b:4c:fc:98:6d:c3:90:d3:34:46:fa:
        af:2d:b7:e9:5e:ce:c0:26:47:db:6c:df:81:75:ed:65:d0:36:
        52:fb:4e:24:be:6e:4a:71:be:81:33:be:4a:3b:8b:46:2a:55:
        bb:d7:05:c7:fe:2b:af:2b:01:2c:8b:2b:e7:04:95:a5:b0:10:
        d9:85:4a:26:44:ba:23:d9:a2:d0:f1:1b:14:97:8f:64:f2:21:
        42:21:41:d2:9f:47:fb:e4:be:01:42:54:92:77:c8:24:b9:7f:
        aa:56:f1:2c
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=New York, L=New York, O=PKCS11 Provider, OU=Testing Harness
        Validity
            Not Before: Feb 20 23:16:45 2023 GMT
            Not After : Feb 20 23:16:45 2024 GMT
        Subject: C=US, O=PKCS11 Provider, CN=OCSP
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b0:73:3a:be:bc:83:33:cb:2a:90:a1:cc:59:39:
                    7e:3f:4f:4d:04:41:9c:6c:8d:95:89:62:b4:00:f6:
                    a2:19:98:9c:ce:b3:fc:4b:e0:9a:8a:2d:69:65:10:
                    cf:02:06:9b:58:cc:b7:7a:8d:23:1d:4f:23:0f:30:
                    27:a2:b8:83:14:48:a3:f8:f8:1b:3c:df:03:7e:7f:
                    be:4b:6d:8b:15:9e:2e:c5:7b:16:9d:80:cd:78:c9:
                    8e:ba:ac:24:20:c1:ce:e7:dd:e7:6f:28:68:cc:08:
                    cd:b5:69:43:66:5a:88:05:eb:6f:36:a1:43:96:5b:
                    58:f8:cf:07:86:bd:90:a9:5a:0b:9a:0c:83:89:64:
                    13:74:d0:d7:e7:8a:4b:ef:7d:6d:c0:5b:e4:aa:9c:
                    5f:e2:f3:2e:ce:f5:3a:5f:6e:e5:b4:f4:85:39:d0:
                    07:43:60:a8:42:86:90:cc:5d:6a:4d:7e:38:bd:de:
                    cf:0c:aa:f3:90:6b:7a:db:31:e1:3b:6f:ef:6c:4e:
                    c3:99:e0:b9:a5:2e:50:f0:ca:17:03:4b:0e:f0:8b:
                    02:5b:26:bc:02:d0:ec:b1:a4:ed:78:fc:2b:85:4b:
                    f8:f4:5a:4d:00:24:ff:a1:cf:d7:e8:9b:3c:03:bc:
                    de:7d:2c:b6:2a:40:5f:25:9d:9a:b0:f5:94:a5:bd:
                    a2:83
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Key Identifier: 
                EC:6A:93:F2:47:91:68:95:7F:9E:94:A3:C6:33:A0:34:1E:27:31:71
            X509v3 Authority Key Identifier: 
                EC:6A:93:F2:47:91:68:95:7F:9E:94:A3:C6:33:A0:34:1E:27:31:71
    SOCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = PKCS11 Provider, CN = OCSP
    Produced At: Feb 20 23:16:45 2023 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 810C6D581B88B8245F66B67E49B738D99BD5F7BB
      Issuer Key Hash: EC6A93F2479168957F9E94A3C633A0341E273171
      Serial Number: 01
    Cert Status: good
    This Update: Feb 20 23:16:45 2023 GMT

    Response Extensions:
        OCSP Nonce: 
            0410F4E71463A3E6C1013B9CFCF0C8CEA11D
    Signature Algorithm: sha1WithRSAEncryption
    Signature Value:
        31:2e:cb:48:d9:a5:e1:80:21:d0:d2:ad:65:e7:97:b9:46:69:
        f2:26:fa:a1:14:b6:49:89:aa:fa:45:97:f3:03:d5:8f:cc:c1:
        a5:83:5e:8f:f5:98:3c:1d:8b:2c:54:c6:cc:dc:26:52:35:fe:
        6e:40:25:ae:cd:33:15:3c:ac:ee:26:ff:43:7d:90:34:65:7a:
        d2:fd:04:c4:fe:d7:5b:7e:91:93:91:06:ac:51:1b:25:b0:e3:
        bf:cf:d1:db:01:5b:09:85:55:e0:97:60:5a:95:57:80:dd:0c:
        a1:f7:a8:1f:90:41:c0:30:b9:d4:b1:c5:ed:f9:11:1a:cd:d1:
        90:1a:83:ed:0b:cf:1e:24:05:77:c2:58:66:00:35:4c:c6:36:
        33:6b:e9:7c:97:04:9c:1b:4c:fc:98:6d:c3:90:d3:34:46:fa:
        af:2d:b7:e9:5e:ce:c0:26:47:db:6c:df:81:75:ed:65:d0:36:
        52:fb:4e:24:be:6e:4a:71:be:81:33:be:4a:3b:8b:46:2a:55:
        bb:d7:05:c7:fe:2b:af:2b:01:2c:8b:2b:e7:04:95:a5:b0:10:
        d9:85:4a:26:44:ba:23:d9:a2:d0:f1:1b:14:97:8f:64:f2:21:
        42:21:41:d2:9f:47:fb:e4:be:01:42:54:92:77:c8:24:b9:7f:
        aa:56:f1:2c
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=New York, L=New York, O=PKCS11 Provider, OU=Testing Harness
        Validity
            Not Before: Feb 20 23:16:45 2023 GMT
            Not After : Feb 20 23:16:45 2024 GMT
        Subject: C=US, O=PKCS11 Provider, CN=OCSP
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b0:73:3a:be:bc:83:33:cb:2a:90:a1:cc:59:39:
                    7e:3f:4f:4d:04:41:9c:6c:8d:95:89:62:b4:00:f6:
                    a2:19:98:9c:ce:b3:fc:4b:e0:9a:8a:2d:69:65:10:
                    cf:02:06:9b:58:cc:b7:7a:8d:23:1d:4f:23:0f:30:
                    27:a2:b8:83:14:48:a3:f8:f8:1b:3c:df:03:7e:7f:
                    be:4b:6d:8b:15:9e:2e:c5:7b:16:9d:80:cd:78:c9:
                    8e:ba:ac:24:20:c1:ce:e7:dd:e7:6f:28:68:cc:08:
                    cd:b5:69:43:66:5a:88:05:eb:6f:36:a1:43:96:5b:
                    58:f8:cf:07:86:bd:90:a9:5a:0b:9a:0c:83:89:64:
                    13:74:d0:d7:e7:8a:4b:ef:7d:6d:c0:5b:e4:aa:9c:
                    5f:e2:f3:2e:ce:f5:3a:5f:6e:e5:b4:f4:85:39:d0:
                    07:43:60:a8:42:86:90:cc:5d:6a:4d:7e:38:bd:de:
                    cf:0c:aa:f3:90:6b:7a:db:31:e1:3b:6f:ef:6c:4e:
                    c3:99:e0:b9:a5:2e:50:f0:ca:17:03:4b:0e:f0:8b:
                    02:5b:26:bc:02:d0:ec:b1:a4:ed:78:fc:2b:85:4b:
                    f8:f4:5a:4d:00:24:ff:a1:cf:d7:e8:9b:3c:03:bc:
                    de:7d:2c:b6:2a:40:5f:25:9d:9a:b0:f5:94:a5:bd:
                    a2:83
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Key Identifier: 
                EC:6A:93:F2:47:91:68:95:7F:9E:94:A3:C6:33:A0:34:1E:27:31:71
            X509v3 Authority Key Identifier: 
                EC:6A:93:F2:47:91:68:95:7F:9E:94:A3:C6:33:A0:34:1E:27:31:71
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        94:7f:31:8e:4c:5a:06:55:f2:76:19:09:d7:fd:12:91:e9:76:
        35:8a:5c:82:5b:a6:91:e1:92:0a:09:73:3b:a7:a2:8b:e1:47:
        82:bb:a5:13:e8:5b:b5:f8:fa:88:9a:74:c0:ec:f2:d4:26:f8:
        29:f9:31:e1:e9:57:5a:79:64:a8:4f:28:87:99:d7:73:1d:ee:
        3c:88:f8:b8:d6:e5:32:71:95:86:96:4f:31:3b:b5:96:89:7e:
        61:fc:70:29:44:d6:a2:51:ea:38:3c:be:4e:9f:16:66:44:eb:
        76:0d:f6:91:97:77:dc:34:e8:5d:e7:ac:db:37:98:74:ac:1c:
        8a:7f:ff:a8:c9:14:e9:60:cc:bd:77:2f:d0:68:df:ef:4d:80:
        58:25:53:a6:19:98:18:03:00:4c:6a:94:72:d9:22:86:6b:2f:
        11:50:db:28:e9:5e:c6:aa:7d:7d:14:ab:ee:4f:c7:77:81:cd:
        a0:d6:4b:85:c3:25:d2:ae:ac:43:23:a7:a9:4b:31:7b:b5:0f:
        aa:10:ee:67:45:42:dd:3e:05:bd:a3:91:83:0a:3a:07:8e:68:
        d6:ee:92:db:75:56:e9:33:da:59:99:a8:88:3a:f8:8f:85:69:
        68:49:54:1a:72:2c:db:41:b0:99:d7:1f:e4:19:37:c1:56:96:
        83:cd:51:46
-----BEGIN CERTIFICATE-----
MIIDcjCCAlqgAwIBAgIBAjANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJVUzER
MA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRgwFgYDVQQKDA9Q
S0NTMTEgUHJvdmlkZXIxGDAWBgNVBAsMD1Rlc3RpbmcgSGFybmVzczAeFw0yMzAy
MjAyMzE2NDVaFw0yNDAyMjAyMzE2NDVaMDYxCzAJBgNVBAYTAlVTMRgwFgYDVQQK
DA9QS0NTMTEgUHJvdmlkZXIxDTALBgNVBAMMBE9DU1AwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCwczq+vIMzyyqQocxZOX4/T00EQZxsjZWJYrQA9qIZ
mJzOs/xL4JqKLWllEM8CBptYzLd6jSMdTyMPMCeiuIMUSKP4+Bs83wN+f75LbYsV
ni7FexadgM14yY66rCQgwc7n3edvKGjMCM21aUNmWogF6282oUOWW1j4zweGvZCp
WguaDIOJZBN00NfnikvvfW3AW+SqnF/i8y7O9TpfbuW09IU50AdDYKhChpDMXWpN
fji93s8MqvOQa3rbMeE7b+9sTsOZ4LmlLlDwyhcDSw7wiwJbJrwC0OyxpO14/CuF
S/j0Wk0AJP+hz9fomzwDvN59LLYqQF8lnZqw9ZSlvaKDAgMBAAGjWjBYMAkGA1Ud
EwQCMAAwCwYDVR0PBAQDAgXgMB0GA1UdDgQWBBTsapPyR5FolX+elKPGM6A0Hicx
cTAfBgNVHSMEGDAWgBTsapPyR5FolX+elKPGM6A0HicxcTANBgkqhkiG9w0BAQsF
AAOCAQEAlH8xjkxaBlXydhkJ1/0Skel2NYpcglumkeGSCglzO6eii+FHgrulE+hb
tfj6iJp0wOzy1Cb4Kfkx4elXWnlkqE8oh5nXcx3uPIj4uNblMnGVhpZPMTu1lol+
YfxwKUTWolHqODy+Tp8WZkTrdg32kZd33DToXees2zeYdKwcin//qMkU6WDMvXcv
0Gjf702AWCVTphmYGAMATGqUctkihmsvEVDbKOlexqp9fRSr7k/Hd4HNoNZLhcMl
0q6sQyOnqUsxe7UPqhDuZ0VC3T4FvaORgwo6B45o1u6S23VW6TPaWZmoiDr4j4Vp
aElUGnIs20Gwmdcf5Bk3wVaWg81RRg==
-----END CERTIFICATE-----
/__w/pkcs11-provider/pkcs11-provider/tests/tmp.softokn/demoCA/cert.pem: good
	This Update: Feb 20 23:16:45 2023 GMT
FAIL democa-softokn (exit status: 127)
```

**Comment by simo5** [comment]
I would like to avoid the fixup that disables the test on Debian.
I'll wait a day or so in case someone has a clue, then will just merge and will re-enable the test on Debian when we can figure out what's the issue.

**Comment by beldmit** [comment]
```
801B3DB32D7F0000:error:40800091:pkcs11:p11prov_GetOperationState:There is no active operation of appropriate type in the specified session:interface.gen.c:279:Error returned by C_GetOperationState
```
What is this message about?

**Comment by simo5** [comment]
> ```
> 801B3DB32D7F0000:error:40800091:pkcs11:p11prov_GetOperationState:There is no active operation of appropriate type in the specified session:interface.gen.c:279:Error returned by C_GetOperationState
> ```
> 
> What is this message about?

This is our attempt to duplicate operations, because that's what OpenSSL does, but most PKCS#11 tokens do not support this operation, so we get these spurious errors.
IT is not impacting anything, just ignore for now (we need to open bugs to OpenSSL, to stop relying on duplication of context in common paths though ...
Duplication should be used only if necessary, and IMO fallbacks should be created in the TLS layer if duplication does not work.

My plan is to then return errors once OpenSSL can handle them.

**Comment by simo5** [comment]
So I just excluded Debian from running the ocsp stuff and I guess we'll just revisit it later.
Meanwhile I'll merge this as it is net more coverage even if partial on Debian

**Pull request merged**
