### PR TITLE
Fix memory leak of ctx_pool.contexts

### PR DESCRIPTION
**Pull request by neverpanic**
#### Description

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2327985

#### Checklist

- [x] Code modified for ~feature~ bug
- [ ] ~Test suite updated with functionality tests~
- [ ] ~Test suite updated with negative tests~
- [ ] ~Documentation updated~

#### Reviewer's checklist:

- [x] Any issues marked for closing are addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible commit messages
- [x] Coverity Scan has run if needed (code PR) and no new defects were found

### CODE REVIEW

**Comment by beldmit** [comment]
@Jakuje I think it's msan, not asan

**Comment by Jakuje** [comment]
> @Jakuje I think it's msan, not asan

I think the asan has lsan module which should detect memory leaks too:

https://clang.llvm.org/docs/LeakSanitizer.html

But it looks like it needs `ASAN_OPTIONS=detect_leaks=1`, which is not present here. Let me add it in separate PR.

The msan on the other hand requires rebuilds of the whole module including dependencies to avoid false positives if I remember well.

**Comment by neverpanic** [comment]
Are the CI failures expected or a side effect of the free?

**Comment by simo5** [comment]
I broke kryoptic CI, I know how to fix it, we do not need to block on it.

**Pull request merged**
