### PR TITLE
Better PSS params defaults handling

### LINKED ISSUE #191: Provider fails PSS signature with piv_II token
**Describe the bug**
```
openssl dgst  -sign "pkcs11:id=%02;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out data_to_sign.bin.sig4 data_to_sign.bin
Enter pass phrase for PKCS#11 Token (Slot 1 - Yubico YubiKey OTP+FIDO+CCID):
$ !2965
openssl dgst  -verify "pkcs11:id=%02;type=public" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature data_to_sign.bin.sig4 data_to_sign.bin
Verified OK
$
$ ykcs11-tool --verify -m SHA384-RSA-PKCS-PSS -d 02 -y pubkey --signature-file data_to_sign.bin.sig4 -i data_to_sign.bin
Using slot 1 with a present token (0x1)
Using signature algorithm SHA384-RSA-PKCS-PSS
PSS parameters: hashAlg=SHA384, mgf=MGF1-SHA384, salt_len=48 B
Invalid signature
$ pkcs11-tool --verify -m SHA384-RSA-PKCS-PSS -d 02 -y pubkey --signature-file data_to_sign.bin.sig4 -i data_to_sign.bin
Using slot 1 with a present token (0x4)
Using signature algorithm SHA384-RSA-PKCS-PSS
PSS parameters: hashAlg=SHA384, mgf=MGF1-SHA384, salt_len=48 B
Invalid signature
$
```

**To Reproduce**
See above.

**Expected behavior**
```
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;id=%02;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out data_to_sign.bin.sig4 data_to_sign.bin
Engine "pkcs11" set.
Enter PKCS#11 token PIN for Blumenthal, Uri (UR20980):
$
$ pkcs11-tool --verify -m SHA384-RSA-PKCS-PSS -d 02 -y pubkey --signature-file data_to_sign.bin.sig4 -i data_to_sign.bin
Using slot 1 with a present token (0x4)
Using signature algorithm SHA384-RSA-PKCS-PSS
PSS parameters: hashAlg=SHA384, mgf=MGF1-SHA384, salt_len=48 B
Signature is valid
$ 
```

**Operating environment (please complete the following information):**
 - OS: MacOS (probably irrelevant)
 - Version: 13.2 (probably irrelevant)

**Token and application used (please complete the following information):**
 - Device: Yubikey-4 PIV applet. Probably, the only thing that matters is that it's (a) physical, and (b) smartdard (PIV).
 - PKCS11 Driver version: current master
 - Application: OpenSSL CLI
 - Version: 3.0.8

### PR DESCRIPTION
**Pull request by simo5**
Improve setting PSS params defaults.
Calculate defaults based on the digest set, but only if mfg and saltlen have not been explicitly set to different values.
Calculate saltlen also for openssl negative default codes and special strings instead of bailing out.

Fixes #191

### CODE REVIEW

**Comment by mouse07410** [comment]
I think this PR can and should be merged. Thanks!

**Review by mouse07410 — APPROVED** [review]
It works on MacOS with smartcards

**Review by Jakuje — APPROVED** [review]
looks ok on the fast review. Are there some softokens supporting some of these parameters that could extend our test coverage? I think softhsm supports very limited amount of these parameters, but at least something would be nice to have

**Comment by simo5** [comment]
@jakuje, pss support is not great yet, but manual testing confirms the right default are chosen, so I am happy with that.

**Pull request merged**
