### PR TITLE
Run Shellcheck as part of CI and squash the shellcheck and yamlint warnings

### PR DESCRIPTION
**Pull request by Jakuje**
Follow-up to #254 where the shell did not do what it was supposed to be doing, I decided to take shellcheck into action and squash the warnings to keep the tests "clean". On the way I also reformatted they github yml files as the editor was going craze every time I had to touch them.

### CODE REVIEW

**Comment by Jakuje** [comment]
> I like this but do not get why the new shellcheck test fails?

The GH action is still WIP. Give me couple of minutes :)

**Comment by Jakuje** [comment]
the shellcheck looks good (hope I did not mess up some functionality with the changes). Homebrew looks broken though.

**Comment by Jakuje** [comment]
> macos is actually failing the uri test now

aaand it works now!

**Review by simo5 — APPROVED** [review]
LGTM

**Pull request merged**
